### ISSUE TITLE
Retrofit으로 값이 안 받아와짐

### ISSUE THREAD

**Issue by HanBI24** [OpenSW-TeamLC/Angel-Kitchen_Server#5]
어제 열어놨을 때 /readdata 확인했는데 값이 안 넘어와서 혹시 내가 잘못한 부분이 있는지 확인좀(깃헙 api는 정상적으로 작동)  
코틀린인데 자바랑 거의 똑같아서 대충 먼 코드인진 알거임  
pull해서 테스트 해보셈  
[테스트 레포](https://github.com/OpenSW-TeamLC/TestLab-Android/tree/master/retroTest/app/src/main/java/hello/world/retrotest)

**Comment by CT-1326** [comment]
지금 서버 닫힘

다음달 Free Dyno 까지 기달려야함
